remote_theme: pages-themes/cayman@v0.2.0

title: Hello! I'm Justin Mach.
description: [My CV:](Justin Mach English Teacher Resume.pdf)

About Me:

🎓 Graduate Student at Hokkaido University's Graduate School of International Media, Communication, and Tourism Studies
My CV:
🔬 Researching The role of soft power in Japanese politics
🌱 Currently focused on learning github and how to use software for research
👯 Open to collaborating on Research Projects
🤔 Passionate about DOGS
💬 Ask me about anything!
📫 How to reach me: LinkedIn
Research Interests:

Main research interests: Japan, Pop culture, soft power, international relations
Secondary research interests: Linguistics, linguistic anthropology
Skills & Expertise:

Languages: English, Japanese
Languages being learnt: Mandarin, Cantonese
Other Relevant Skills: Teaching English as a Second Language
Publications & Presentations:

Bachelor Thesis: Reimagining Shonen Manga: Tatsuki Fujimoto’s Innovative Use of Narrative and Aesthetics in Chainsaw Man

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jemoji
url: https://justinmach.github.io/
markdown: kramdown
